# Generated by Django 3.1.2 on 2020-10-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('Num_count', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ID_Imagen', models.CharField(max_length=100)),
                ('Clase_Prediccion', models.CharField(max_length=20)),
                ('Porcentaje_Clase1', models.FloatField(blank=True, default=None, null=True)),
                ('Porcentaje_Clase2', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
